<h2 style="background-color: lightblue; padding: 10px;">
Electric Vehicle Adoption and Market Analysis 
</h2>

In [ ]:
This project focuses on analyzing electric vehicle population data to understand the patterns and trends in EV adoption. The analysis will examine factors such as vehicle type, manufacturer, model year, electric range, geographic distribution, and CAFV eligibility to identify trends in EV usage and adoption.

Focuses on:
1.EV adoption trends:
   * Analyze the number of EVs by model year.
   * Identify whether EV adoption is increasing over time
2.Geographical analysis:
   * Study EV distribution by county, city, state, and postal code.
   * Identify areas with higher concentrations of EVs.
3.Manufaturer and model analysis:
  * Find the most common EV manufacturers.
  * Identify popular EV models.
  * Compare different manufacturers based on electric range.
4.Electric vehicle type:
  * Compare Battery Electric Vehicles (BEV) and Plug-in Hybrid Electric Vehicles    (PHEV).
  * Analyze their distribution across locations and years.
5.Electric range analysis:
   * Examine the distribution of electric driving range.
   * Compare electric range across manufacturers, models, and vehicle types.
6.CAFV Eligibility:
   * Analyze the Clean Alternative Fuel Vehicle (CAFV) Eligibility categories.
   * Study how eligibility varies by vehicle type and model year.

<h2 style="background-color: lightblue; padding: 10px;">
Column Description
</h2>

In [ ]:
VIN (1-10):
The first 10 characters of the vehicle identification number used to identify the vehicle

County:
The county where the electric vehicle is registered

City:
The city where the electric vehicle is registered.

State:
The state where the electric vehicle is registered.

Postal Code:
The postal/ZIP code associated with the vehicle's registration location.

Model Year:
The year in which the electric vehicle model was manufactured.

Make:
The manufacturer or brand of the electric vehicle.

Model:
The specific model name of the electric vehicle.

Electric Vehicle Type:
Indicates whether the vehicle is a Battery Electric Vehicle (BEV) or Plug-in Hybrid Electric Vehicle (PHEV).

Clean Alternative Fuel Vehicle (CAFV) Eligibility:
Indicates whether the vehicle meets the eligibility requirements for clean alternative fuel vehicle programs.

Electric Range:
The estimated distance the vehicle can travel using electric power on a full charge, measured in miles.

Base MSRP:
The manufacturer's suggested retail price of the vehicle's base model.

Legislative District:
The political legislative district in which the vehicle is registered.

DOL Vehicle ID:
The unique identification number assigned to the vehicle by the Department of Licensing.

Vehicle Location:
The geographic location of the vehicle registration, generally represented using latitude and longitude coordinates.

Electric Utility:
The electric utility company serving the vehicle's registered location.

2020 Census Tract:
The census tract in which the vehicle is registered, based on 2020 Census geographic boundaries.

## Data loading and initial overview

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("export.csv")

In [4]:
df

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 GEOID
0,1N4AZ1CP3K,King,Shoreline,WA,98155.0,2019,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,150.0,32.0,168526641,POINT (-122.30304 47.75494),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303302e+10
1,WBY8P4C51K,King,Kirkland,WA,98033.0,2019,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,126.0,48.0,9418181,POINT (-122.2066 47.67887),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
2,3FA6P0SU8G,Snohomish,Lynnwood,WA,98036.0,2016,FORD,FUSION,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,19.0,1.0,172853495,POINT (-122.29245 47.82557),PUGET SOUND ENERGY INC,5.306105e+10
3,5YJ3E1EB3N,Yakima,Wapato,WA,98951.0,2022,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,15.0,204768175,POINT (-120.42083 46.44779),PACIFICORP,5.307794e+10
4,WBY1Z2C53F,King,Renton,WA,98055.0,2015,BMW,I3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,81.0,11.0,269262920,POINT (-122.19488 47.44034),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299700,ZACPDFDW7R,Kitsap,Port Orchard,WA,98312.0,2024,DODGE,HORNET,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,32.0,26.0,278485665,POINT (-122.65223 47.57192),PUGET SOUND ENERGY INC,5.303509e+10
299701,KM8KMDAF3P,Grant,Ephrata,WA,98823.0,2023,HYUNDAI,IONIQ 5,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,13.0,223872596,POINT (-119.55096 47.31909),PUD NO 2 OF GRANT COUNTY,5.302501e+10
299702,1GT10BDD5S,Kitsap,Poulsbo,WA,98370.0,2025,GMC,HUMMER EV PICKUP,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,23.0,280685807,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,5.303509e+10
299703,5YJ3E1EB8N,Snohomish,Everett,WA,98208.0,2022,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,44.0,214860208,POINT (-122.22478 47.91564),PUGET SOUND ENERGY INC,5.306104e+10
299704,JM3KKCHA9T,King,Duvall,WA,98019.0,2026,MAZDA,CX-90,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,27.0,45.0,292954399,POINT (-121.98609 47.74068),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10

In [6]:
# check the number of rows and columns
df.shape

(299705, 16)

In [7]:
df.columns

Index(['VIN (1-10)', 'County', 'City', 'State', 'Postal Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Legislative District', 'DOL Vehicle ID', 'Vehicle Location',
       'Electric Utility', '2020 GEOID'],
      dtype='object')

In [8]:
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 GEOID
0,1N4AZ1CP3K,King,Shoreline,WA,98155.0,2019,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,150.0,32.0,168526641,POINT (-122.30304 47.75494),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303302e+10
1,WBY8P4C51K,King,Kirkland,WA,98033.0,2019,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,126.0,48.0,9418181,POINT (-122.2066 47.67887),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
2,3FA6P0SU8G,Snohomish,Lynnwood,WA,98036.0,2016,FORD,FUSION,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,19.0,1.0,172853495,POINT (-122.29245 47.82557),PUGET SOUND ENERGY INC,5.306105e+10
3,5YJ3E1EB3N,Yakima,Wapato,WA,98951.0,2022,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,15.0,204768175,POINT (-120.42083 46.44779),PACIFICORP,5.307794e+10
4,WBY1Z2C53F,King,Renton,WA,98055.0,2015,BMW,I3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,81.0,11.0,269262920,POINT (-122.19488 47.44034),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299705 entries, 0 to 299704
Data columns (total 16 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         299705 non-null  object
 1   County                                             299694 non-null  object
 2   City                                               299694 non-null  object
 3   State                                              299705 non-null  object
 4   Postal Code                                        299694 non-null  float64
 5   Model Year                                         299705 non-null  int64
 6   Make                                               299705 non-null  object
 7   Model                                              299705 non-null  object
 8   Electric Vehicle Type                              299705 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  299705 non-null  object
 10  Electric Range                                     299679 non-null  float64
 11  Legislative District                               298915 non-null  float64
 12  DOL Vehicle ID                                     299705 non-null  int64
 13  Vehicle Location                                   299685 non-null  object
 14  Electric Utility                                   299694 non-null  object
 15  2020 GEOID                                         299694 non-null  float64
dtypes: float64(4), int64(2), object(10)
memory usage: 36.6+ MB

In [10]:
df.describe()

,Postal Code,Model Year,Electric Range,Legislative District,DOL Vehicle ID,2020 GEOID
count,299694.000000,299705.000000,299679.000000,298915.000000,2.997050e+05,2.996940e+05
mean,98176.001962,2022.344666,36.663313,28.754589,2.509924e+08,5.296742e+10
std,2652.053836,3.093007,76.034423,14.892388,6.238702e+07,1.687605e+09
min,1030.000000,1999.000000,0.000000,1.000000,4.469000e+03,1.001020e+09
25%,98052.000000,2021.000000,0.000000,17.000000,2.283017e+08,5.303301e+10
50%,98134.000000,2023.000000,0.000000,32.000000,2.679271e+08,5.303303e+10
75%,98391.000000,2024.000000,32.000000,42.000000,2.845359e+08,5.305394e+10
max,99801.000000,2027.000000,337.000000,49.000000,4.791150e+08,6.601095e+10

In [11]:
df.isnull().sum()

VIN (1-10)                                             0
County                                                11
City                                                  11
State                                                  0
Postal Code                                           11
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                        26
Legislative District                                 790
DOL Vehicle ID                                         0
Vehicle Location                                      20
Electric Utility                                      11
2020 GEOID                                            11
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

# Data Pre-Processing

In [14]:
# Handel missing values
# For numerivcal columns use median
numerical_columns = [
    'Postal Code',
    'Electric Range',
    'Legislative District',
    '2020 GEOID']
for column in numerical_columns:
    df[column] = df[column].fillna(df[column].median())

In [15]:
# For Categorical columns use mode
categorical_columns = [
    'County',
    'City',
    'Vehicle Location',
    'Electric Utility']
for column in categorical_columns:
    df[column] = df[column].fillna(df[column].mode()[0])

In [16]:
df.isnull().sum()

VIN (1-10)                                           0
County                                               0
City                                                 0
State                                                0
Postal Code                                          0
Model Year                                           0
Make                                                 0
Model                                                0
Electric Vehicle Type                                0
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0
Electric Range                                       0
Legislative District                                 0
DOL Vehicle ID                                       0
Vehicle Location                                     0
Electric Utility                                     0
2020 GEOID                                           0
dtype: int64

## No duplicates rows

In [17]:
# correct data types

df.dtypes

VIN (1-10)                                            object
County                                                object
City                                                  object
State                                                 object
Postal Code                                          float64
Model Year                                             int64
Make                                                  object
Model                                                 object
Electric Vehicle Type                                 object
Clean Alternative Fuel Vehicle (CAFV) Eligibility     object
Electric Range                                       float64
Legislative District                                 float64
DOL Vehicle ID                                         int64
Vehicle Location                                      object
Electric Utility                                      object
2020 GEOID                                           float64
dtype: object

In [18]:
df['Postal Code'] = df['Postal Code'].astype(int)
df['Model Year'] = df['Model Year'].astype(int)
df['Electric Range'] = df['Electric Range'].astype(float)
df['Legislative District'] = df['Legislative District'].astype(int)
df['DOL Vehicle ID'] = df['DOL Vehicle ID'].astype(int)
df['2020 GEOID'] = df['2020 GEOID'].astype(int)

In [19]:
df.dtypes

VIN (1-10)                                            object
County                                                object
City                                                  object
State                                                 object
Postal Code                                            int64
Model Year                                             int64
Make                                                  object
Model                                                 object
Electric Vehicle Type                                 object
Clean Alternative Fuel Vehicle (CAFV) Eligibility     object
Electric Range                                       float64
Legislative District                                   int64
DOL Vehicle ID                                         int64
Vehicle Location                                      object
Electric Utility                                      object
2020 GEOID                                             int64
dtype: object

In [20]:
# creating derived columns
# Create vehicle age

current_year = 2026
df['Vehicle Age'] = current_year - df['Model Year']

In [21]:
df[['Model Year', 'Vehicle Age']].head()

   Model Year  Vehicle Age
0        2019            7
1        2019            7
2        2016           10
3        2022            4
4        2015           11

In [22]:
# Create range category
def range_category(x):
    if x < 100:
        return 'Low Range'
    elif x < 200:
        return 'Medium Range'
    else:
        return 'High Range'
df['Range Category'] = df['Electric Range'].apply(range_category)

In [23]:
df[['Electric Range', 'Range Category']].head()

   Electric Range Range Category
0           150.0   Medium Range
1           126.0   Medium Range
2            19.0      Low Range
3             0.0      Low Range
4            81.0      Low Range

In [27]:
# Filtering
#Find Tesla vehicles
tesla_df = df[df['Make'] == 'TESLA']
tesla_df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 GEOID,Vehicle Age,Range Category
3,5YJ3E1EB3N,Yakima,Wapato,WA,98951,2022,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,15,204768175,POINT (-120.42083 46.44779),PACIFICORP,53077940008,4,Low Range
9,5YJ3E1EB6L,Kitsap,Silverdale,WA,98383,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,322.0,23,6335647,POINT (-122.69275 47.65171),PUGET SOUND ENERGY INC,53035091302,6,High Range
12,5YJYGDEE8M,Yakima,Selah,WA,98942,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,15,236581355,POINT (-120.53145 46.65405),PACIFICORP,53077003200,5,Low Range
16,5YJ3E1EB8J,Yakima,Yakima,WA,98902,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,15,474530486,POINT (-120.51904 46.59782),PACIFICORP,53077001201,8,High Range
23,5YJ3E1EA7J,King,Redmond,WA,98052,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,48,475127782,POINT (-122.13158 47.67858),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),53033022606,8,High Range

In [28]:
#Vehicles with electric range>200
high_range = df[df['Electric Range'] > 200]
high_range.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 GEOID,Vehicle Age,Range Category
5,1G1FZ6S00L,Island,Greenbank,WA,98253,2020,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,259.0,10,268491597,POINT (-122.56817 48.08827),PUGET SOUND ENERGY INC,53029971302,6,High Range
7,KM8K53AG7L,Thurston,Olympia,WA,98512,2020,HYUNDAI,KONA,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,258.0,35,138948988,POINT (-123.04078 46.94792),PUGET SOUND ENERGY INC,53067011822,6,High Range
9,5YJ3E1EB6L,Kitsap,Silverdale,WA,98383,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,322.0,23,6335647,POINT (-122.69275 47.65171),PUGET SOUND ENERGY INC,53035091302,6,High Range
13,KNDCC3LG4L,Thurston,Olympia,WA,98502,2020,KIA,NIRO,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,239.0,22,152199932,POINT (-122.92018 47.04575),PUGET SOUND ENERGY INC,53067010520,6,High Range
16,5YJ3E1EB8J,Yakima,Yakima,WA,98902,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,15,474530486,POINT (-120.51904 46.59782),PACIFICORP,53077001201,8,High Range

In [29]:
#Battery electric vehicles
bev = df[df['Electric Vehicle Type'] == 'Battery Electric Vehicle (BEV)']
bev.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 GEOID,Vehicle Age,Range Category
0,1N4AZ1CP3K,King,Shoreline,WA,98155,2019,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,150.0,32,168526641,POINT (-122.30304 47.75494),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033020500,7,Medium Range
3,5YJ3E1EB3N,Yakima,Wapato,WA,98951,2022,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,15,204768175,POINT (-120.42083 46.44779),PACIFICORP,53077940008,4,Low Range
4,WBY1Z2C53F,King,Renton,WA,98055,2015,BMW,I3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,81.0,11,269262920,POINT (-122.19488 47.44034),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),53033025805,11,Low Range
5,1G1FZ6S00L,Island,Greenbank,WA,98253,2020,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,259.0,10,268491597,POINT (-122.56817 48.08827),PUGET SOUND ENERGY INC,53029971302,6,High Range
6,KM8HC3A66R,Snohomish,Monroe,WA,98272,2024,HYUNDAI,KONA,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,39,270749790,POINT (-121.98087 47.8526),PUGET SOUND ENERGY INC,53061052207,2,Low Range

In [30]:
#vehicles from Seattle
seattle = df[df['City'] == 'Seattle']
seattle.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 GEOID,Vehicle Age,Range Category
24,1N4AZ0CP3E,King,Seattle,WA,98125,2014,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,46,250490705,POINT (-122.29639 47.71558),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033001100,12,Low Range
32,5YJ3E1EB7K,King,Seattle,WA,98115,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220.0,46,305583925,POINT (-122.3185 47.67949),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033002000,7,High Range
56,3MW5P9J00M,King,Seattle,WA,98122,2021,BMW,330E,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,20.0,43,264786483,POINT (-122.30875 47.60921),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033007503,5,Low Range
58,5UX43EU0XT,King,Seattle,WA,98177,2026,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,38.0,36,290292838,POINT (-122.37238 47.74068),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033001600,0,Low Range
93,WBY1Z6C31H,King,Seattle,WA,98122,2017,BMW,I3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,81.0,43,348137597,POINT (-122.30875 47.60921),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033007901,9,Low Range

In [31]:
#Aggregation
#Number of vehicles by manufacturer
vehicles_by_make = df.groupby('Make').size().sort_values(ascending=False)
vehicles_by_make.head(10)

Make
TESLA        122981
CHEVROLET     20236
FORD          16118
NISSAN        16053
KIA           14776
TOYOTA        13998
BMW           12356
HYUNDAI       12351
RIVIAN         9817
VOLVO          8187
dtype: int64

In [32]:
#Average electric range by manufacturer
avg_range = df.groupby('Make')['Electric Range'].mean().sort_values(ascending=False)
avg_range.head(10)

Make
JAGUAR                  155.430657
WHEEGO ELECTRIC CARS    100.000000
TH!NK                   100.000000
CHEVROLET                74.634117
FIAT                     73.169195
NISSAN                   62.685168
SMART                    61.504673
AZURE DYNAMICS           56.000000
LAND ROVER               50.932540
TESLA                    47.607785
Name: Electric Range, dtype: float64

In [33]:
#Number of vehicles by EV type
ev_type_count = df.groupby('Electric Vehicle Type').size()
ev_type_count

Electric Vehicle Type
Battery Electric Vehicle (BEV)            241724
Plug-in Hybrid Electric Vehicle (PHEV)     57981
dtype: int64

In [34]:
#Number of vehicles by model year
year_count = df.groupby('Model Year').size()
year_count

Model Year
1999        3
2000        8
2002        1
2003        1
2008       17
2010       19
2011      529
2012     1290
2013     3851
2014     3151
2015     4381
2016     5031
2017     8431
2018    13982
2019    10827
2020    12191
2021    20872
2022    30278
2023    61595
2024    49413
2025    37007
2026    36272
2027      555
dtype: int64

In [35]:
#Number of vehicles by city
city_count = df.groupby('City').size().sort_values(ascending=False)
city_count.head(10)

City
Seattle      45480
Bellevue     14386
Vancouver    11215
Redmond      10135
Bothell       9819
Kirkland      8487
Sammamish     8129
Renton        7897
Olympia       7016
Tacoma        6651
dtype: int64

In [36]:
# Replace abbreviations
state_mapping = {
    'WA': 'Washington',
    'CA': 'California',
    'VA': 'Virginia',
    'MD': 'Maryland',
    'FL': 'Florida',
    'TX': 'Texas',
    'NV': 'Nevada',
    'OR': 'Oregon',
    'CO': 'Colorado',
    'NC': 'North Carolina',
    'AZ': 'Arizona',
    'IL': 'Illinois',
    'GA': 'Georgia',
    'NY': 'New York',
    'MO': 'Missouri',
    'NJ': 'New Jersey',
    'DC': 'District of Columbia',
    'ID': 'Idaho',
    'MI': 'Michigan',
    'AL': 'Alabama',
    'MA': 'Massachusetts',
    'TN': 'Tennessee',
    'PA': 'Pennsylvania',
    'SC': 'South Carolina',
    'NE': 'Nebraska',
    'RI': 'Rhode Island',
    'CT': 'Connecticut',
    'OH': 'Ohio',
    'KY': 'Kentucky',
    'KS': 'Kansas',
    'LA': 'Louisiana',
    'NM': 'New Mexico',
    'NH': 'New Hampshire',
    'WI': 'Wisconsin',
    'IN': 'Indiana',
    'UT': 'Utah',
    'HI': 'Hawaii',
    'MN': 'Minnesota',
    'WY': 'Wyoming',
    'SD': 'South Dakota',
    'AR': 'Arkansas',
    'OK': 'Oklahoma',
    'AK': 'Alaska',
    'IA': 'Iowa',
    'ME': 'Maine',
    'MT': 'Montana',
    'DE': 'Delaware',
    'MS': 'Mississippi'}
df['State'] = df['State'].replace(state_mapping)

In [38]:
df

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 GEOID,Vehicle Age,Range Category
0,1N4AZ1CP3K,King,Shoreline,Washington,98155,2019,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,150.0,32,168526641,POINT (-122.30304 47.75494),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033020500,7,Medium Range
1,WBY8P4C51K,King,Kirkland,Washington,98033,2019,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,126.0,48,9418181,POINT (-122.2066 47.67887),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),53033022703,7,Medium Range
2,3FA6P0SU8G,Snohomish,Lynnwood,Washington,98036,2016,FORD,FUSION,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,19.0,1,172853495,POINT (-122.29245 47.82557),PUGET SOUND ENERGY INC,53061051932,10,Low Range
3,5YJ3E1EB3N,Yakima,Wapato,Washington,98951,2022,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,15,204768175,POINT (-120.42083 46.44779),PACIFICORP,53077940008,4,Low Range
4,WBY1Z2C53F,King,Renton,Washington,98055,2015,BMW,I3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,81.0,11,269262920,POINT (-122.19488 47.44034),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),53033025805,11,Low Range
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299700,ZACPDFDW7R,Kitsap,Port Orchard,Washington,98312,2024,DODGE,HORNET,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,32.0,26,278485665,POINT (-122.65223 47.57192),PUGET SOUND ENERGY INC,53035092102,2,Low Range
299701,KM8KMDAF3P,Grant,Ephrata,Washington,98823,2023,HYUNDAI,IONIQ 5,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,13,223872596,POINT (-119.55096 47.31909),PUD NO 2 OF GRANT COUNTY,53025010402,3,Low Range
299702,1GT10BDD5S,Kitsap,Poulsbo,Washington,98370,2025,GMC,HUMMER EV PICKUP,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,23,280685807,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,53035090201,1,Low Range
299703,5YJ3E1EB8N,Snohomish,Everett,Washington,98208,2022,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,44,214860208,POINT (-122.22478 47.91564),PUGET SOUND ENERGY INC,53061041606,4,Low Range
299704,JM3KKCHA9T,King,Duvall,Washington,98019,2026,MAZDA,CX-90,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,27.0,45,292954399,POINT (-121.98609 47.74068),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),53033032401,0,Low Range